### ISSUE TITLE
web-server 单独分开怎么处理？

### ISSUE THREAD

**Issue by xieyuanbin1** [sex-pomelo/sex-pomelo#6]
web-server端想单独分出来，做成独立的一个项目，但是不知道怎么连接，连接的时候总是会报错：

![image](https://user-images.githubusercontent.com/9530270/65028189-3debbc00-d96e-11e9-9d83-d40a03bac61b.png)

**Comment by shudingbo** [comment]
你是想把 chat 里的web server独立用？ 这个本来就是独立的啊。 参见 文档 [chat源码下载与安装](https://github.com/NetEase/pomelo/wiki/chat%E6%BA%90%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8E%E5%AE%89%E8%A3%85l)

**Comment by xieyuanbin1** [comment]
> 你是想把 chat 里的web server独立用？ 这个本来就是独立的啊。 参见 文档 [chat源码下载与安装](https://github.com/NetEase/pomelo/wiki/chat%E6%BA%90%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8E%E5%AE%89%E8%A3%85l)

我的意思是把前端做成单独的项目，独立部署，这个还是放在一起的。
如果只是聊天功能，game-server端就不需要动了，只需要给web-server添加功能更新然后打包部署，放到服务器上，而不需要再放到这个里面，现在每次前端打包，都要再复制放过来

**Comment by shudingbo** [comment]
> > 你是想把 chat 里的web server独立用？ 这个本来就是独立的啊。 参见 文档 [chat源码下载与安装](https://github.com/NetEase/pomelo/wiki/chat%E6%BA%90%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8E%E5%AE%89%E8%A3%85l)
> 
> 我的意思是把前端做成单独的项目，独立部署，这个还是放在一起的。
> 如果只是聊天功能，game-server端就不需要动了，只需要给web-server添加功能更新然后打包部署，放到服务器上，而不需要再放到这个里面，现在每次前端打包，都要再复制放过来

你把 web-server文件夹 复制到任意路径，npm install -d 就行了。
1. 修改 app.js 里面的web server 端口号;
2. 修改client.js 里面的 pomeo.init 函数调用的地方，更改 服务器地址和端口

**Comment by xieyuanbin1** [comment]
> > > 你是想把 chat 里的web server独立用？ 这个本来就是独立的啊。 参见 文档 [chat源码下载与安装](https://github.com/NetEase/pomelo/wiki/chat%E6%BA%90%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8E%E5%AE%89%E8%A3%85l)
> > 
> > 
> > 我的意思是把前端做成单独的项目，独立部署，这个还是放在一起的。
> > 如果只是聊天功能，game-server端就不需要动了，只需要给web-server添加功能更新然后打包部署，放到服务器上，而不需要再放到这个里面，现在每次前端打包，都要再复制放过来
> 
> 你把 web-server文件夹 复制到任意路径，npm install -d 就行了。
> 
> 1. 修改 app.js 里面的web server 端口号;
> 2. 修改client.js 里面的 pomeo.init 函数调用的地方，更改 服务器地址和端口

ok! thanks!
