### ISSUE TITLE
log

### ISSUE THREAD

**Issue by yunmin97** [sex-pomelo/sex-pomelo#7]
问题：
const logger = require('@sex-pomelo/sex-pomelo-logger').getLogger(__filename);
logger.info('xxx');
logger.warn('xxx');
logger.error('xxx');
log 无法输出到终端控制台上（但是logs目录下对应xx.log文件里有），如何配置log4js.json才能既输出到控制台又记录到logs文件下的xx.log文件?

版本：sex-pomleo 2.2.20
系统：win 10
node版本：8.11.4

**Comment by shudingbo** [comment]
log4js的文档

**Comment by shudingbo** [comment]
log4js.json里加 console，具体参见log4js的文档
