### ISSUE TITLE
Compatible with node14

### ISSUE THREAD

**Issue by shudingbo** [sex-pomelo/sex-pomelo#8]
1. Cliff module has warning.
  * Cliff only used in bin/pomelo. Rewrite **clifflite** module replace

**Comment by yunmin97** [comment]
1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方

**Comment by shudingbo** [comment]
> 1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
> 2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方

谢谢您的建议 :)

> 1. App helper Class 是一个辅助类，原有的方式仍然是可以的。 原有的方式主要有个问题:
 比如只想在某一类服务，加载某些组件/配置/插件...，原有的方式，所有的服务器都require这些东东，哪怕根本不需要。这就导致了一些不必要的消耗（内存，CPU）。

> 2. sex-pomelo 目前依赖升级还是比较及时的， 甚至有些依赖功能因为ES6本身就包含，就直接重写不再依赖了。`npm install @sex-pomeo/sex-pomelo` 时的警告几乎没有

**Comment by yunmin97** [comment]
> 
> 
> > 1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
> > 2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方
> 
> 谢谢您的建议 :)
> 
> > 1. App helper Class 是一个辅助类，原有的方式仍然是可以的。 原有的方式主要有个问题:
> >    比如只想在某一类服务，加载某些组件/配置/插件...，原有的方式，所有的服务器都require这些东东，哪怕根本不需要。这就导致了一些不必要的消耗（内存，CPU）。
> 
> > 1. sex-pomelo 目前依赖升级还是比较及时的， 甚至有些依赖功能因为ES6本身就包含，就直接重写不再依赖了。`npm install @sex-pomeo/sex-pomelo` 时的警告几乎没有

1、 require不放外面，应该可以解决某些东东被所有服务器都require的情况。兼容原有的模式就行（开发者各取所爱）。
app.configure('production|development', 'http', function () {
    // 放进这里，应该就只有http服务器才会require了
    let json = require('pomelo-json-plugin');
    ...
});
2、我也是看见sex重写了一些东西才开始关注的，生态插件如果得到维护就更好了。

**Comment by shudingbo** [comment]
几乎

> > > 1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
> > > 2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方
> > 
> > 
> > 谢谢您的建议 :)
> > > 1. App helper Class 是一个辅助类，原有的方式仍然是可以的。 原有的方式主要有个问题:
> > >    比如只想在某一类服务，加载某些组件/配置/插件...，原有的方式，所有的服务器都require这些东东，哪怕根本不需要。这就导致了一些不必要的消耗（内存，CPU）。
> > 
> > 
> > > 1. sex-pomelo 目前依赖升级还是比较及时的， 甚至有些依赖功能因为ES6本身就包含，就直接重写不再依赖了。`npm install @sex-pomeo/sex-pomelo` 时的警告几乎没有
> 
> 1、 require不放外面，应该可以解决某些东东被所有服务器都require的情况。兼容原有的模式就行（开发者各取所爱）。
> app.configure('production|development', 'http', function () {
> // 放进这里，应该就只有http服务器才会require了
> let json = require('pomelo-json-plugin');
> ...
> });
> 2、我也是看见sex重写了一些东西才开始关注的，生态插件如果得到维护就更好了。

sex里fork过来的库都是做过更改的，尤其 admin 和 pomeo 改了不少。 你有空可以看看前面的发布日志或者 history

**Comment by shudingbo** [comment]
> > > 1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
> > > 2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方
> > 
> > 
> > 谢谢您的建议 :)
> > > 1. App helper Class 是一个辅助类，原有的方式仍然是可以的。 原有的方式主要有个问题:
> > >    比如只想在某一类服务，加载某些组件/配置/插件...，原有的方式，所有的服务器都require这些东东，哪怕根本不需要。这就导致了一些不必要的消耗（内存，CPU）。
> > 
> > 
> > > 1. sex-pomelo 目前依赖升级还是比较及时的， 甚至有些依赖功能因为ES6本身就包含，就直接重写不再依赖了。`npm install @sex-pomeo/sex-pomelo` 时的警告几乎没有
> 
> 1、 require不放外面，应该可以解决某些东东被所有服务器都require的情况。兼容原有的模式就行（开发者各取所爱）。
> app.configure('production|development', 'http', function () {
> // 放进这里，应该就只有http服务器才会require了
> let json = require('pomelo-json-plugin');
> ...
> });
> 2、我也是看见sex重写了一些东西才开始关注的，生态插件如果得到维护就更好了。

sex里fork过来的库都是做过更改的，尤其 admin 和 pomeo 改了不少。 你有空可以看看前面的发布日志或者 history。
另外，如果您觉得好用，麻烦稍稍推广下

**Comment by yunmin97** [comment]
> > > > 1、App helper Class 这个感觉用起来有点复杂化了，没有之前的方式简单明了，特别是config.js
> > > > 2、developer-friendly可以有，但是性能优化和项目依赖库的升级可能才是吸引眼球的地方
> > > 
> > > 
> > > 谢谢您的建议 :)
> > > > 1. App helper Class 是一个辅助类，原有的方式仍然是可以的。 原有的方式主要有个问题:
> > > >    比如只想在某一类服务，加载某些组件/配置/插件...，原有的方式，所有的服务器都require这些东东，哪怕根本不需要。这就导致了一些不必要的消耗（内存，CPU）。
> > > 
> > > 
> > > > 1. sex-pomelo 目前依赖升级还是比较及时的， 甚至有些依赖功能因为ES6本身就包含，就直接重写不再依赖了。`npm install @sex-pomeo/sex-pomelo` 时的警告几乎没有
> > 
> > 
> > 1、 require不放外面，应该可以解决某些东东被所有服务器都require的情况。兼容原有的模式就行（开发者各取所爱）。
> > app.configure('production|development', 'http', function () {
> > // 放进这里，应该就只有http服务器才会require了
> > let json = require('pomelo-json-plugin');
> > ...
> > });
> > 2、我也是看见sex重写了一些东西才开始关注的，生态插件如果得到维护就更好了。
> 
> sex里fork过来的库都是做过更改的，尤其 admin 和 pomeo 改了不少。 你有空可以看看前面的发布日志或者 history。
> 另外，如果您觉得好用，麻烦稍稍推广下

没有商业项目辅助，太难了
